export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";

export const USER_LOGIN_BEGIN = "USER_LOGIN_BEGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_UPDATE_BEGIN = "USER_UPDATE_BEGIN";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";

export const USER_CREATE_BEGIN = "USER_CREATE_BEGIN";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_ERROR = "USER_CREATE_ERROR";

export const CLEAR_ALERT = "CLEAR_ALERT";

export const USER_LOGOUT = "USER_LOGOUT";

export const ADMIN_GET_ALL_USER_BEGIN = "ADMIN_GET_ALL_USER_BEGIN";
export const ADMIN_GET_ALL_USER_SUCCESS = "ADMIN_GET_ALL_USER_SUCCESS";
export const ADMIN_GET_ALL_USER_ERROR = "ADMIN_GET_ALL_USER_ERROR";

export const ADMIN_DELETE_USER_BEGIN = "ADMIN_DELETE_USER_BEGIN";
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELTE_USER_BEGIN";
export const ADMIN_DELETE_USER_ERROR = "ADMIN_DELTE_USER_ERROR";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const DISPLAY_TAG_ALERT = "DISPLAY_TAG_ALERT";

export const THUMBNAIL_UPLOAD_BEGIN = "THUMBNAIL_UPLOAD_BEGIN";
export const THUMBNAIL_UPLOAD_SUCCESS = "THUMBNAIL_UPLOAD_SUCCESS";
export const THUMBNAIL_UPLOAD_ERROR = "THUMBNAIL_UPLOAD_ERROR";

export const THUMBNAIL_GET_ALL_BEGIN = "THUMBNAIL_GET_ALL_BEGIN";
export const THUMBNAIL_GET_ALL_SUCCESS = "THUMBNAIL_GET_ALL_SUCCESS";
export const THUMBNAIL_GET_ALL_ERROR = "THUMBNAIL_GET_ERROR";

export const VIDEO_CREATE_BEGIN = "VIDEO_CREATE_BEGIN";
export const VIDEO_CREATE_SUCCESS = "VIDEO_CREATE_SUCCESS";
export const VIDEO_CREATE_ERROR = "VIDEO_CREATE_ERROR";

export const VIDEO_GET_BY_AUTH_BEGIN = "VIDEO_GET_BY_AUTH_BEGIN";
export const VIDEO_GET_BY_AUTH_SUCCESS = "VIDEO_GET_BY_AUTH_SUCCESS";
export const VIDEO_GET_BY_AUTH_ERROR = "VIDEO_GET_BY_AUTH_ERROR";

export const VIDEO_GET_ALL_BEGIN = "VIDEO_GET_ALL_BEGIN";
export const VIDEO_GET_ALL_SUCCESS = "VIDEO_GET_ALL_SUCCESS";
export const VIDEO_GET_ALL_ERROR = "VIDEO_GET_ALL_ERROR";

export const VIDEO_UPDATE_BEGIN = "VIDEO_UPDATE_BEGIN";
export const VIDEO_UPDATE_SUCCESS = "VIDEO_UPDATE_SUCCESS";
export const VIDEO_UPDATE_ERROR = "VIDEO_UPDATE_ERROR";

export const SHOW_TAGS_MODAL = "SHOW_TAGS_MODAL";
export const HIDE_TAGS_MODAL = "HIDE_TAGS_MODAL";

export const SAVE_TAG = "SAVE_TAG";

export const VIDEO_DELETE_BEGIN = "VIDEO_DELETE_BEGIN";
export const VIDEO_DELETE_SUCCESS = "VIDEO_DELETE_SUCCESS";
export const VIDEO_DELETE_ERROR = "VIDEO_DELETE_ERROR";

export const PAGINATIO_SET_PAGE = "PAGINATION_SET_PAGE";

export const SEARCH_SET_VALUE = "SEARCH_SET_VALUE";

export const VIDEO_HOME_GET_ALL_BEGIN = "VIDEO_HOME_GET_ALL_BEGIN";
export const VIDEO_HOME_GET_ALL_SUCCESS = "VIDEO_HOME_GET_ALL_SUCCESS";
export const VIDEO_HOME_GET_ALL_ERROR = "VIDEO_HOME_GET_ALL_ERROR";

export const SHOW_SIDEBAR = "SHOW_SIDEBAR";
export const HIDE_SIDEBAR = "HIDE_SIDEBAR";

export const ADD_LIST_TAG = "ADD_LIST_TAG";

export const VIDEO_GET_BY_ID_BEGIN = "VIDEO_GET_BY_ID_BEGIN";
export const VIDEO_GET_BY_ID_SUCCESS = "VIDEO_GET_BY_ID_SUCCESS";
export const VIDEO_GET_BY_ID_ERROR = "VIDEO_GET_BY_ID_ERROR";

export const COMMENT_ADD_BEGIN = "COMMENT_ADD_BEGIN";
export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS";
export const COMMENT_ADD_ERROR = "COMMENT_ADD_ERROR";
